import {
  Landmark,
  LayoutDashboard,
  PieChart,
  Settings,
  Tag,
  Target,
  Truck,
  Users,
  Wallet,
  Zap,
  CreditCard,
  Building2,
  TrendingUp,
  BarChart3,
  FileText,
  GitBranch,
  CalendarClock,
  FileBarChart,
  RefreshCw,
  Bot,
  Brain,
  MessageSquare,
  AlertTriangle,
  GitCompare,
  ScrollText,
} from "lucide-react";

const routes = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
    color: "text-sky-500",
  },
  {
    label: "Transações",
    icon: Wallet,
    href: "/transactions",
    color: "text-violet-500",
  },
  {
    label: "Contas",
    icon: Landmark,
    href: "/accounts",
    color: "text-blue-500",
  },
  {
    label: "Cartões",
    icon: CreditCard,
    href: "/credit-cards",
    color: "text-indigo-500",
  },
  {
    label: "Orçamentos",
    icon: PieChart,
    href: "/budgets",
    color: "text-rose-500",
  },
  {
    label: "Metas",
    icon: Target,
    href: "/goals",
    color: "text-amber-500",
  },
  {
    label: "Dívidas",
    icon: AlertTriangle,
    href: "/debts",
    color: "text-red-500",
  },
  {
    label: "Categorias",
    icon: Tag,
    href: "/categories",
    color: "text-pink-700",
  },
  {
    label: "Centros de Custo",
    icon: Building2,
    href: "/cost-centers",
    color: "text-cyan-500",
  },
  {
    label: "Fornecedores",
    icon: Truck,
    href: "/suppliers",
    color: "text-orange-700",
  },
  {
    label: "Fluxo de Caixa",
    icon: TrendingUp,
    href: "/cash-flow",
    color: "text-green-500",
  },
  {
    label: "DRE",
    icon: FileText,
    href: "/dre",
    color: "text-emerald-500",
  },
  {
    label: "Insights",
    icon: BarChart3,
    href: "/insights",
    color: "text-purple-500",
  },
  {
    label: "Previsão",
    icon: TrendingUp,
    href: "/forecast",
    color: "text-teal-500",
  },
  {
    label: "Automação",
    icon: GitBranch,
    href: "/automation",
    color: "text-orange-500",
  },
  {
    label: "Agendamentos",
    icon: CalendarClock,
    href: "/scheduled",
    color: "text-blue-400",
  },
  {
    label: "Relatórios",
    icon: FileBarChart,
    href: "/reports",
    color: "text-slate-500",
  },
  {
    label: "Comparativos",
    icon: GitCompare,
    href: "/comparisons",
    color: "text-violet-600",
  },
  {
    label: "Conciliação",
    icon: RefreshCw,
    href: "/reconciliation",
    color: "text-cyan-600",
  },
  {
    label: "Assistente IA",
    icon: Bot,
    href: "/ai-assistant",
    color: "text-pink-500",
  },
  {
    label: "Auditoria",
    icon: ScrollText,
    href: "/audit",
    color: "text-gray-500",
  },
  {
    label: "Regras",
    icon: Zap,
    href: "/rules",
    color: "text-yellow-500",
  },
  {
    label: "Usuários",
    icon: Users,
    href: "/users",
    color: "text-emerald-500",
  },
  {
    label: "Perfil",
    icon: Settings,
    href: "/profiles",
  },
];

export { routes };
